#!/bin/bash
set -e
cd "$(dirname "$0")"
APP="LocalMind.app"
BIN="$APP/Contents/MacOS/LocalMind"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Local Mind</string>
  <key>CFBundleDisplayName</key><string>Local Mind</string>
  <key>CFBundleExecutable</key><string>LocalMind</string>
  <key>CFBundleIdentifier</key><string>com.pearce.localmind</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>26.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSSupportsAutomaticTermination</key><true/>
</dict>
</plist>
PLIST

# Stamp the build with where it came from, so the updater can compare against
# the repo and knows which checkout to rebuild.
SRC_DIR="$(pwd)"
SHA="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
SHORT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
WHEN="$(git log -1 --format=%cI 2>/dev/null || echo unknown)"
REMOTE="$(git config --get remote.origin.url 2>/dev/null | sed 's#.*github.com[:/]##; s#\.git$##' || echo '')"
cat > Sources/BuildInfo.swift <<SWIFT
// GENERATED BY build.sh — do not edit, your changes will be overwritten.
enum BuildInfo {
    static let commit      = "$SHA"
    static let shortCommit = "$SHORT"
    static let committedAt = "$WHEN"
    static let repo        = "$REMOTE"
    static let sourceDir   = "$SRC_DIR"
}
SWIFT

echo "==> compiling"
swiftc -O -parse-as-library -swift-version 6 \
  -target arm64-apple-macosx26.0 \
  Sources/*.swift \
  -o "$BIN"

if [ -f Icon/AppIcon.icns ]; then
  cp Icon/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
  echo "==> app icon installed"
fi

IDENTITY="LocalMind Dev"
if security find-certificate -c "$IDENTITY" >/dev/null 2>&1; then
  echo "==> signing with $IDENTITY (stable identity — TCC grants survive rebuilds)"
  codesign --force --sign "$IDENTITY" "$APP"
else
  echo "==> signing (ad-hoc — WARNING: screen permissions reset on every rebuild)"
  codesign --force --sign - "$APP"
fi

echo "==> built $APP"
